### ISSUE TITLE
RSel Highlights chokes on en-US name for Freeway type

### ISSUE THREAD

**Issue by sketchh** [WazeDev/WME-Road-Selector-Highlights#1]
Any road type check that includes the type now named "Freeway (Interstate/Other)" in US English will cause RSel Highlights to choke and display this error and change the type to "undefined".
<img width="321" alt="Screen Shot 2019-04-25 at 13 13 29" src="https://user-images.githubusercontent.com/31964244/56758321-f4e76100-675b-11e9-83a5-9186dda29fa6.png">

**Comment by justins83** [comment]
This is fixed! Wahooo!
